ekf_localization_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # odom data
    odom0: /odom
    odom0_config: [true, true, false,
                   true, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, true]

    # IMU data
    imu0: /imu/data
    imu0_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   true, true, true,
                   true, true, true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    odom0: /odom_cartographer
    odom0_config: [false, false, false,  # XYZ速度
                  false, false, false,  # XYZ角速度
                  false, false, false, # 加速度は不使用
                  false, false, false,
                  false, false, false]
