ekf_localization_node_params:
  ros__parameters:
    use_sim_time: false
    publish_frequency: 30.0
    two_d_mode: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # Left wheel velocity
    odom0: /left_vel
    odom0_config: [true, false, false,
                   false, false, false,
                   true, false, false,
                   false, false, false,
                   false, false, false]

    # Right wheel velocity
    odom1: /right_vel
    odom1_config: [true, false, false,
                   false, false, false,
                   true, false, false,
                   false, false, false,
                   false, false, false]

    # IMU data
    imu0: /left_wheel_imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  true, true, true]
    imu0_remove_gravitational_acceleration: true

    # Covariances and other parameters can be set here
