ekf_localization_node_params:
  ros__parameters:
    use_sim_time: false
    publish_frequency: 30.0
    two_d_mode: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # Left wheel velocity
    odom0: /left_vel
    odom0_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # Right wheel velocity
    odom1: /right_vel
    odom1_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # IMU data
    imu0: /left_wheel_imu
    imu0_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    imu0_remove_gravitational_acceleration: true

    odom0: /odom_cartographer
    odom0_config: [true, true, false,  # XYZ速度
                  false, false, true,  # XYZ角速度
                  false, false, false, # 加速度は不使用
                  false, false, false,
                  false, false, false]
