ekf_localization_node:
  ros__parameters:
    use_sim_time: false
    publish_frequency: 30.0
    two_d_mode: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"
    imu0: true
    imu0_config: [false, false, false,
                   false, false, false,
                   false, false, false,
                   true, true, true,
                   true, true, true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
