ekf_localization_node:
  ros__parameters:
    use_sim_time: false  # Whether to use simulation time
    frequency: 30.0  # Frequency at which to run the filter
    two_d_mode: true  # Limit EKF to 2D motion
    publish_tf: true  # Publish transformation frames
    map_frame: map  # Frame that represents the map
    odom_frame: odom  # Frame that represents odometry
    base_link_frame: base_link  # Frame that represents the robot base
    world_frame: odom  # World frame for localization data
    sensor_timeout: 0.1  # Timeout for sensor data receipt
    transform_time_offset: 0.0  # Time offset for the transformation
    transform_timeout: 0.0  # Timeout for transformation publication
    print_diagnostics: true  # Print diagnostics information

    # Odometry data configuration
    odom0: /odometry/odom_encoder  # Odometry topic
    odom0_config: [true, true, false,  # Configure XYZ position
                   false, false, false,  # Configure XYZ velocity
                   false, false, false,  # Configure XYZ acceleration
                   false, false, true,  # Configure Yaw angle
                   false, false, false]  # Not used
    odom0_differential: false  # Use differential odometry
    odom0_relative: false  # Use relative odometry
    odom0_queue_size: 10  # Queue size for odometry messages
    odom0_nodelay: false  # No delay in odometry processing

    # IMU data configuration
    imu0: /imu/data_filtered  # IMU topic
    imu0_config: [false, false, false,  # No position
                   false, false, false,  # No velocity
                   false, false, false,  # No acceleration
                   true, true, true,  # Orientation (Roll, Pitch, Yaw)
                   true, true, true]  # Angular velocities (Roll, Pitch, Yaw)
    imu0_differential: false  # Use differential IMU data
    imu0_relative: false  # Use relative IMU data
    imu0_queue_size: 10  # Queue size for IMU messages
    imu0_remove_gravitational_acceleration: true  # Remove gravitational acceleration from IMU data
    imu0_nodelay: false  # No delay in IMU data processing

    # Initial estimate covariance matrix
    initial_estimate_covariance: [1e-3, 0, 0, 0, 0, 0,
                                  0, 1e-3, 0, 0, 0, 0,
                                  0, 0, 1e-3, 0, 0, 0,
                                  0, 0, 0, 1e-3, 0, 0,
                                  0, 0, 0, 0, 1e-3, 0,
                                  0, 0, 0, 0, 0, 1e-3]

    # Process noise covariance matrix
    process_noise_covariance: [ 1e-5, 0, 0, 0, 0, 0,
                                0, 1e-5, 0, 0, 0, 0,
                                0, 0, 1e-5, 0, 0, 0,
                                0, 0, 0, 1e-5, 0, 0,
                                0, 0, 0, 0, 1e-5, 0,
                                0, 0, 0, 0, 0, 1e-5]

    # Measurement noise covariance matrix
    measurement_noise_covariance: [1e-3, 0, 0, 0, 0, 0,
                                  0, 1e-3, 0, 0, 0, 0,
                                  0, 0, 1e-3, 0, 0, 0,
                                  0, 0, 0, 1e-3, 0, 0,
                                  0, 0, 0, 0, 1e-3, 0,
                                  0, 0, 0, 0, 0, 1e-3]