joy_node:
  ros__parameters:
    # Name of the joystick device as recognized by the system
    device_name: "Logitech Gamepad F710"
    
    # Deadzone threshold to ignore minor joystick movements
    deadzone: 0.1
    
    # Rate (in Hz) at which joystick inputs are automatically repeated
    autorepeat_rate: 20.0

teleop_twist_joy:
  ros__parameters:
    # Use simulation time (false for real robots)
    use_sim_time: false
    
    # Mapping for linear velocity control
    axis_linear.x: 4  # Vertical axis of the right joystick (confirmed via jstest)
    scale_linear.x: 0.1  # Scaling factor for linear velocity (positive value)
    
    # Mapping for angular velocity control
    axis_angular.yaw: 3  # Horizontal axis of the right joystick (confirmed via jstest)
    scale_angular.yaw: 0.1  # Scaling factor for angular velocity (negative to invert direction)
    
    # Button configuration
    enable_button: 4  # Left shoulder button to enable teleoperation
    enable_turbo_button: 5  # Right shoulder button to toggle turbo mode

    # Turbo mode scaling factor
    scale_linear_turbo.x: 0.3  # Scaling factor multiplier when turbo mode is active
    scale_angular_turbo.yaw: 0.6  # Scaling factor multiplier when turbo mode is active

    # Timeout for sending Twist messages (in seconds)
    twist_timeout: 0.5  # If no input is received within this duration, velocities reset to zero
    
    # Deadzone threshold to ignore minor joystick movements
    deadzone: 0.1  # Ensures small, unintended joystick movements are ignored
    
    # Rate (in Hz) at which Twist messages are automatically repeated
    autorepeat_rate: 20.0  # Provides smooth and continuous command updates
    
